spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/auth?autoReconnect=true
    username: sshs0702
    password: Tjdtks@1607
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
# session
server:
  servlet:
    session:
      timeout: 10m # 기본이 30분이고 최소는 1분입니다.